"""Inject build and per-page source dates into MkDocs metadata.

``build_date`` remains a last-resort fallback. Paper JSON-LD should use the
page's real source date instead, otherwise every build makes every page look
fresh to Google.
"""

from __future__ import annotations

from datetime import date, datetime
from pathlib import Path
import json
import re
import subprocess


RAW_ANGLE_TOKEN_RE = re.compile(
    r"<(?=(?:\d|[.;=]|/?>(?!\w)|/[A-Z][A-Z0-9_-]*>|[A-Z][A-Z0-9_-]*>))"
)
_GIT_DATES_BY_REPO: dict[Path, dict[str, str]] = {}
_GIT_REPO_ROOT_BY_START: dict[Path, Path | None] = {}


def _patch_mkdocs_raw_html_scanner():
    """Allow Markdown text tokens like `<;>` without rewriting source notes."""
    try:
        import mkdocs.structure.pages as pages
    except Exception:  # pragma: no cover
        return

    preprocessor = getattr(pages, "_RawHTMLPreprocessor", None)
    handler = getattr(pages, "_HTMLHandler", None)
    if preprocessor is None or handler is None:
        return
    if getattr(preprocessor, "_paper_notes_angle_patch", False):
        return

    def run(self, lines):
        parser = handler()
        scanner_text = RAW_ANGLE_TOKEN_RE.sub("&lt;", "\n".join(lines))
        parser.feed(scanner_text)
        parser.close()
        self.present_anchor_ids = parser.present_anchor_ids
        return lines

    preprocessor.run = run
    preprocessor._paper_notes_angle_patch = True


def _normalise_date(value) -> str | None:
    if not value:
        return None
    if isinstance(value, datetime):
        return value.date().isoformat()
    if isinstance(value, date):
        return value.isoformat()
    text = str(value).strip()
    match = re.match(r"^(\d{4}-\d{2}-\d{2})", text)
    return match.group(1) if match else None


def _git_repo_root(start: Path) -> Path | None:
    start = start.resolve()
    if start in _GIT_REPO_ROOT_BY_START:
        return _GIT_REPO_ROOT_BY_START[start]
    try:
        result = subprocess.run(
            ["git", "-C", str(start), "rev-parse", "--show-toplevel"],
            check=True,
            capture_output=True,
            text=True,
        )
    except Exception:
        _GIT_REPO_ROOT_BY_START[start] = None
        return None
    repo = Path(result.stdout.strip()).resolve()
    _GIT_REPO_ROOT_BY_START[start] = repo
    return repo


def _git_modified_dates(repo: Path) -> dict[str, str]:
    cached = _GIT_DATES_BY_REPO.get(repo)
    if cached is not None:
        return cached

    dates: dict[str, str] = {}
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), "log", "--name-only", "--format=@@DATE@@%cs"],
            check=True,
            capture_output=True,
            text=True,
        )
    except Exception:
        _GIT_DATES_BY_REPO[repo] = dates
        return dates

    current_date: str | None = None
    for raw_line in result.stdout.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("@@DATE@@"):
            current_date = line.removeprefix("@@DATE@@")
            continue
        if current_date and line not in dates:
            dates[line] = current_date

    _GIT_DATES_BY_REPO[repo] = dates
    return dates


def _file_mtime_date(path: Path) -> str | None:
    try:
        return datetime.fromtimestamp(path.stat().st_mtime).date().isoformat()
    except OSError:
        return None


def _source_modified_date(path: Path, docs_dir: Path) -> str | None:
    repo = _git_repo_root(docs_dir)
    if repo:
        try:
            relpath = path.resolve().relative_to(repo).as_posix()
        except ValueError:
            relpath = None
        if relpath:
            git_date = _git_modified_dates(repo).get(relpath)
            if git_date:
                return git_date
    return _file_mtime_date(path)


def _page_source_path(page, docs_dir: Path) -> Path | None:
    if not page or not getattr(page, "file", None):
        return None
    abs_src_path = getattr(page.file, "abs_src_path", None)
    if abs_src_path:
        return Path(abs_src_path).resolve()
    src_uri = getattr(page.file, "src_uri", None)
    if src_uri:
        return (docs_dir / src_uri).resolve()
    return None


def on_config(config, **kwargs):
    _patch_mkdocs_raw_html_scanner()

    extra = config.setdefault("extra", {})
    extra["build_date"] = date.today().isoformat()

    # Load bilingual URL intersection generated by parent script.
    # Templates emit hreflang only for these URLs to avoid en-side 404s.
    cfg_path = Path(config["config_file_path"]).resolve().parent
    pairs_file = cfg_path / ".hreflang_pairs.json"
    pairs: set[str] = set()
    if pairs_file.exists():
        try:
            pairs = set(json.loads(pairs_file.read_text(encoding="utf-8")))
        except Exception as e:  # pragma: no cover
            print(f"[hreflang] Warning: failed to load {pairs_file}: {e}")
    else:
        print(f"[hreflang] Note: {pairs_file} not found — hreflang tags disabled")
    extra["hreflang_pairs"] = pairs

    return config


def on_page_context(context, page, config, **kwargs):
    docs_dir = Path(config["docs_dir"]).resolve()
    source_path = _page_source_path(page, docs_dir)
    source_modified = _source_modified_date(source_path, docs_dir) if source_path else None

    explicit_date = _normalise_date(page.meta.get("date"))
    fallback = config.get("extra", {}).get("build_date", "")
    page.meta["date_published"] = explicit_date or source_modified or fallback
    page.meta["date_modified"] = source_modified or explicit_date or fallback
    return context
